name: "Sync branches"
description: "GitHub Action to, upon successful merge, open a pull request to sync the updated branch back to one or more other branches."
branding:
  icon: git-pull-request
  color: green
inputs:
  GITHUB_TOKEN:
    description: "User token to be associated with this pull request."
    required: true
  FROM_BRANCH:
    description: "Branch from make pull-request from"
    required: true
  TO_BRANCH:
    description: "Branch to make the pull-request against"
    required: true
  PULL_REQUEST_TITLE:
    description: "What you would like as the title of the pull request. Default: 'sync: {FROM_BRANCH} to {TO_BRANCH}'"
    required: false
  PULL_REQUEST_BODY:
    description: "What you would like in the body of the pull request. Default: 'New code has just landed in {fromBranch} so let's bring {toBranch} up to speed!'"
    required: false
  PULL_REQUEST_IS_DRAFT:
    description: "Set to 'y' for the pull request to be opened as a draft. Default: 'n'"
    required: false
outputs:
  PULL_REQUEST_URL:
    description: "URL for either the generated pull request or the currently open one"
runs:
  using: "node12"
  main: "dist/index.js"
